Algoritmo "exercicio16"
//Escreva um algoritmo que leia três números inteiros e positivos

Var

 a, b, c, r: real

Inicio
      escreval("Digite o primeiro números sendo inteiro e positivo")
      leia(a)
      escreval("Digite o segundo números sendo inteiro e positivo")
      leia(b)
      escreval("Digite o terceiro números sendo inteiro e positivo")
      leia(c)
      
      r<-(((a+b)*(a+b)) + ((b+c)*(b+c)))/2

      escreval("O resultado da expressão eh:", r)
      
Fimalgoritmo