Algoritmo "exercicio3"
// Dadas 3 notas fazer um algoritmo para calcular a média aritmética

Var
   nota1, nota2, nota3, resultado: real
   
Inicio

    escreval("Digita a nota 1:")
    leia(nota1)
    escreval("Digita a nota 2:")
    leia(nota2)
    escreval("Digita a nota 3:")
    leia(nota3)

    resultado <- (nota1+nota2+nota3)/3
 
    escreval("A sua média aritmética eh:", resultado)
    
Fimalgoritmo