Algoritmo "exercicio9"
// Dado um número, calcule a sua tabuada e imprima na tela

Var

   tabuada, primeiro, ultimo, x: inteiro


Inicio

      escreval("Digite a tabuada:")
      leia(tabuada)
        escreval("Digite o primeiro número:")
      leia(primeiro)
        escreval("Digite o último número:")
      leia(ultimo)
      
      para x de primeiro ate ultimo faca
           escreval(tabuada, " *", x, " =", tabuada*x)
      fimpara

Fimalgoritmo