Algoritmo "exercicio7"
// Fazer um algoritmo que leia as 3 notas de um aluno e calcule a média final deste aluno

Var
   nota1, nota2, nota3, media : real


Inicio
      escreval("Digite a primeira nota:")
      leia(nota1)
      escreval("Digite a segunda nota:")
      leia(nota2)
      escreval("Digite a terceira nota:")
      leia(nota3)

      media <- (nota1+nota2+nota3) / (2+3+5)
      
      escreval("A média final deste aluno é:", media)
      
Fimalgoritmo